# Generated by Django 2.1.4 on 2018-12-13 07:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cliente', models.CharField(max_length=255)),
                ('direccion_cliente', models.CharField(max_length=255)),
                ('ciudad_cliente', models.CharField(max_length=255)),
                ('comuna_cliente', models.CharField(max_length=255)),
                ('telefono_cliente', models.IntegerField()),
                ('correo_cliente', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('tarea_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('inicio_atencion', models.TimeField(blank=True)),
                ('termino_atencion', models.TimeField(blank=True)),
                ('id_ascensor', models.CharField(max_length=63)),
                ('modelo_ascensor', models.CharField(max_length=255)),
                ('fallas_detectadas', models.TextField()),
                ('reparaciones_efectuadas', models.TextField()),
                ('piezas_cambiadas', models.TextField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id_tecnico', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tecnico', models.CharField(max_length=255)),
                ('correo', models.CharField(max_length=255)),
                ('contraseña', models.CharField(max_length=16)),
            ],
        ),
        migrations.AddField(
            model_name='tarea',
            name='tecnico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Tecnico'),
        ),
    ]
